// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF9ruEtkBX4eMpHWWszHekv6lAk-RYc40',
    appId: '1:708091445021:web:2073fcd5970d6794892bf4',
    messagingSenderId: '708091445021',
    projectId: 'shsalfa-5a67b',
    authDomain: 'shsalfa-5a67b.firebaseapp.com',
    storageBucket: 'shsalfa-5a67b.firebasestorage.app',
    measurementId: 'G-CDKTKD01CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3SJ7SE3n5Q-dEYy1-bGN9dWiLWXcor4',
    appId: '1:708091445021:android:cf94fcbf230823f1892bf4',
    messagingSenderId: '708091445021',
    projectId: 'shsalfa-5a67b',
    storageBucket: 'shsalfa-5a67b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5pAeb0ElzMiPj1T8lQGSvfphaoYGe09U',
    appId: '1:708091445021:ios:79233966e101fe2b892bf4',
    messagingSenderId: '708091445021',
    projectId: 'shsalfa-5a67b',
    storageBucket: 'shsalfa-5a67b.firebasestorage.app',
    iosBundleId: 'com.example.hagz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5pAeb0ElzMiPj1T8lQGSvfphaoYGe09U',
    appId: '1:708091445021:ios:79233966e101fe2b892bf4',
    messagingSenderId: '708091445021',
    projectId: 'shsalfa-5a67b',
    storageBucket: 'shsalfa-5a67b.firebasestorage.app',
    iosBundleId: 'com.example.hagz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF9ruEtkBX4eMpHWWszHekv6lAk-RYc40',
    appId: '1:708091445021:web:8fa264be5ef0d7b2892bf4',
    messagingSenderId: '708091445021',
    projectId: 'shsalfa-5a67b',
    authDomain: 'shsalfa-5a67b.firebaseapp.com',
    storageBucket: 'shsalfa-5a67b.firebasestorage.app',
    measurementId: 'G-DDHGZ1N7L1',
  );
}
